name: fuzz-for-10mins
on: [push]
jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Prepare Environment
        run: sudo apt install clang-14 libgss-dev
      - name: Fuzzing
        run: ./fuzzer/build-and-fuzz.sh 60

